export type MetricPlatform = 'meta' | 'google';
export type MetricSection =
  | 'kpi_cards'
  | 'charts'
  | 'funnel'
  | 'contact'
  | 'campaign_table'
  | 'report_summary'
  | 'placement_table'
  | 'demographic_breakdown'
  | 'geographic_map'
  | 'device_table'
  | 'keyword_table'
  | 'search_terms_table';
export type RegistryFieldKind = 'metric' | 'dimension';
export type RegistryFieldFormat = 'number' | 'currency' | 'percentage' | 'text';
export type RegistryAggregation = 'sum' | 'avg' | 'ratio' | 'derived' | 'none';

export interface RegistryField {
  key: string;
  kind: RegistryFieldKind;
  label: string;
  format: RegistryFieldFormat;
  description: string;
  platforms: MetricPlatform[];
  sections: MetricSection[];
  sourceFields: Partial<Record<MetricPlatform, string[]>>;
  aggregation: RegistryAggregation;
}

export const REGISTRY_METRICS: RegistryField[] = [
  {
    key: 'totalSpend',
    kind: 'metric',
    label: 'Wydatki',
    format: 'currency',
    description: 'Łączne wydatki reklamowe',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown', 'geographic_map', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['spend'], google: ['spend'] },
    aggregation: 'sum',
  },
  {
    key: 'totalImpressions',
    kind: 'metric',
    label: 'Wyświetlenia',
    format: 'number',
    description: 'Łączna liczba wyświetleń reklam',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['impressions'], google: ['impressions'] },
    aggregation: 'sum',
  },
  {
    key: 'totalClicks',
    kind: 'metric',
    label: 'Kliknięcia',
    format: 'number',
    description: 'Łączna liczba kliknięć',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown', 'geographic_map', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['clicks', 'inline_link_clicks'], google: ['clicks'] },
    aggregation: 'sum',
  },
  {
    key: 'totalConversions',
    kind: 'metric',
    label: 'Konwersje',
    format: 'number',
    description: 'Łączna liczba konwersji',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table', 'geographic_map', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['conversions'], google: ['conversions'] },
    aggregation: 'sum',
  },
  {
    key: 'averageCtr',
    kind: 'metric',
    label: 'Średni CTR',
    format: 'percentage',
    description: 'Średni współczynnik klikalności',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['ctr', 'inline_link_click_ctr'], google: ['ctr'] },
    aggregation: 'ratio',
  },
  {
    key: 'averageCpc',
    kind: 'metric',
    label: 'Średni CPC',
    format: 'currency',
    description: 'Średni koszt kliknięcia',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['cpc', 'cost_per_inline_link_click'], google: ['cpc'] },
    aggregation: 'ratio',
  },
  {
    key: 'reach',
    kind: 'metric',
    label: 'Zasięg',
    format: 'number',
    description: 'Unikalna liczba osób, które zobaczyły reklamę',
    platforms: ['meta'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['reach'] },
    aggregation: 'sum',
  },
  {
    key: 'frequency',
    kind: 'metric',
    label: 'Częstotliwość',
    format: 'number',
    description: 'Średnia liczba wyświetleń na użytkownika',
    platforms: ['meta'],
    sections: ['kpi_cards', 'charts', 'report_summary'],
    sourceFields: { meta: ['frequency'] },
    aggregation: 'avg',
  },
  {
    key: 'cpm',
    kind: 'metric',
    label: 'CPM',
    format: 'currency',
    description: 'Koszt za 1000 wyświetleń',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['cpm'], google: ['cpm'] },
    aggregation: 'ratio',
  },
  {
    key: 'cpp',
    kind: 'metric',
    label: 'CPP',
    format: 'currency',
    description: 'Koszt za zasięg',
    platforms: ['meta'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['cpp'] },
    aggregation: 'ratio',
  },
  {
    key: 'reservations',
    kind: 'metric',
    label: 'Rezerwacje',
    format: 'number',
    description: 'Łączna liczba rezerwacji',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'contact', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown'],
    sourceFields: { meta: ['reservations'], google: ['reservations'] },
    aggregation: 'sum',
  },
  {
    key: 'reservation_value',
    kind: 'metric',
    label: 'Wartość rezerwacji',
    format: 'currency',
    description: 'Łączna wartość monetarna rezerwacji',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'contact', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown'],
    sourceFields: { meta: ['reservation_value'], google: ['reservation_value'] },
    aggregation: 'sum',
  },
  {
    key: 'roas',
    kind: 'metric',
    label: 'ROAS',
    format: 'number',
    description: 'Return on Ad Spend',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'report_summary', 'campaign_table', 'placement_table', 'demographic_breakdown', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['roas'], google: ['roas'] },
    aggregation: 'ratio',
  },
  {
    key: 'cost_per_reservation',
    kind: 'metric',
    label: 'Koszt rezerwacji',
    format: 'currency',
    description: 'Średni koszt pozyskania jednej rezerwacji',
    platforms: ['meta', 'google'],
    sections: ['contact', 'report_summary', 'campaign_table', 'demographic_breakdown'],
    sourceFields: { meta: ['cost_per_reservation'], google: ['cost_per_reservation'] },
    aggregation: 'ratio',
  },
  {
    key: 'offline_reservations',
    kind: 'metric',
    label: 'Rezerwacje offline',
    format: 'number',
    description: 'Szacowana liczba rezerwacji offline z kontaktów telefonicznych i e-mail',
    platforms: ['meta', 'google'],
    sections: ['contact', 'report_summary'],
    sourceFields: { meta: ['email_contacts', 'click_to_call'], google: ['email_contacts', 'click_to_call'] },
    aggregation: 'derived',
  },
  {
    key: 'offline_value',
    kind: 'metric',
    label: 'Wartość offline',
    format: 'currency',
    description: 'Szacowana wartość potencjalnych rezerwacji offline',
    platforms: ['meta', 'google'],
    sections: ['contact', 'report_summary'],
    sourceFields: { meta: ['offline_reservations', 'reservation_value'], google: ['offline_reservations', 'reservation_value'] },
    aggregation: 'derived',
  },
  {
    key: 'total_value_with_offline',
    kind: 'metric',
    label: 'Łączna wartość online + offline',
    format: 'currency',
    description: 'Łączna wartość konwersji online i potencjalnych konwersji offline',
    platforms: ['meta', 'google'],
    sections: ['contact', 'report_summary'],
    sourceFields: { meta: ['total_conversion_value', 'offline_value'], google: ['total_conversion_value', 'offline_value'] },
    aggregation: 'derived',
  },
  {
    key: 'cost_percentage',
    kind: 'metric',
    label: 'Koszt pozyskania rezerwacji',
    format: 'percentage',
    description: 'Udział wydatków reklamowych w łącznej wartości konwersji online i offline',
    platforms: ['meta', 'google'],
    sections: ['contact', 'report_summary'],
    sourceFields: { meta: ['totalSpend', 'total_value_with_offline'], google: ['totalSpend', 'total_value_with_offline'] },
    aggregation: 'derived',
  },
  {
    key: 'click_to_call',
    kind: 'metric',
    label: 'Kliknięcia - telefon',
    format: 'number',
    description: 'Kliknięcia prowadzące do połączenia telefonicznego',
    platforms: ['meta', 'google'],
    sections: ['charts', 'contact', 'demographic_breakdown'],
    sourceFields: { meta: ['click_to_call'], google: ['click_to_call'] },
    aggregation: 'sum',
  },
  {
    key: 'email_contacts',
    kind: 'metric',
    label: 'Kontakty e-mail',
    format: 'number',
    description: 'Kontakty inicjowane przez e-mail',
    platforms: ['meta', 'google'],
    sections: ['charts', 'contact', 'demographic_breakdown'],
    sourceFields: { meta: ['email_contacts'], google: ['email_contacts'] },
    aggregation: 'sum',
  },
  {
    key: 'booking_step_1',
    kind: 'metric',
    label: 'Wyszukiwania',
    format: 'number',
    description: 'Booking step 1',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'demographic_breakdown'],
    sourceFields: { meta: ['booking_step_1'], google: ['booking_step_1'] },
    aggregation: 'sum',
  },
  {
    key: 'booking_step_2',
    kind: 'metric',
    label: 'Wyświetlenia zawartości',
    format: 'number',
    description: 'Booking step 2',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'demographic_breakdown'],
    sourceFields: { meta: ['booking_step_2'], google: ['booking_step_2'] },
    aggregation: 'sum',
  },
  {
    key: 'booking_step_3',
    kind: 'metric',
    label: 'Inicjacje kasy',
    format: 'number',
    description: 'Booking step 3',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'demographic_breakdown'],
    sourceFields: { meta: ['booking_step_3'], google: ['booking_step_3'] },
    aggregation: 'sum',
  },
  {
    key: 'conversion_value',
    kind: 'metric',
    label: 'Wartość konwersji',
    format: 'currency',
    description: 'Wartość konwersji',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'report_summary', 'campaign_table', 'geographic_map', 'device_table', 'keyword_table', 'search_terms_table'],
    sourceFields: { meta: ['conversion_value'], google: ['conversion_value'] },
    aggregation: 'sum',
  },
  {
    key: 'total_conversion_value',
    kind: 'metric',
    label: 'Łączna wartość konwersji',
    format: 'currency',
    description: 'Łączna wartość wszystkich konwersji',
    platforms: ['meta', 'google'],
    sections: ['charts', 'funnel', 'contact', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['total_conversion_value'], google: ['total_conversion_value'] },
    aggregation: 'sum',
  },
  {
    key: 'averageCpa',
    kind: 'metric',
    label: 'Średni CPA',
    format: 'currency',
    description: 'Średni koszt pozyskania konwersji',
    platforms: ['meta', 'google'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['cpa'], google: ['cpa'] },
    aggregation: 'ratio',
  },
  {
    key: 'inline_link_clicks',
    kind: 'metric',
    label: 'Kliknięcia w link',
    format: 'number',
    description: 'Meta inline link clicks',
    platforms: ['meta'],
    sections: ['kpi_cards', 'charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['inline_link_clicks'] },
    aggregation: 'sum',
  },
  {
    key: 'lead',
    kind: 'metric',
    label: 'Leady',
    format: 'number',
    description: 'Liczba wygenerowanych leadów',
    platforms: ['meta'],
    sections: ['charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['lead'] },
    aggregation: 'sum',
  },
  {
    key: 'purchase',
    kind: 'metric',
    label: 'Zakupy',
    format: 'number',
    description: 'Liczba zakupów',
    platforms: ['meta', 'google'],
    sections: ['charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['purchase'], google: ['purchase'] },
    aggregation: 'sum',
  },
  {
    key: 'purchase_value',
    kind: 'metric',
    label: 'Wartość zakupów',
    format: 'currency',
    description: 'Łączna wartość zakupów',
    platforms: ['meta', 'google'],
    sections: ['charts', 'report_summary', 'campaign_table'],
    sourceFields: { meta: ['purchase_value'], google: ['purchase_value'] },
    aggregation: 'sum',
  },
];

export const REGISTRY_DIMENSIONS: RegistryField[] = [
  {
    key: 'campaign_name',
    kind: 'dimension',
    label: 'Kampania',
    format: 'text',
    description: 'Nazwa kampanii',
    platforms: ['meta', 'google'],
    sections: ['campaign_table', 'search_terms_table'],
    sourceFields: { meta: ['campaign_name'], google: ['campaign_name'] },
    aggregation: 'none',
  },
  {
    key: 'objective',
    kind: 'dimension',
    label: 'Cel kampanii',
    format: 'text',
    description: 'Cel lub typ kampanii reklamowej',
    platforms: ['meta'],
    sections: ['campaign_table'],
    sourceFields: { meta: ['objective'] },
    aggregation: 'none',
  },
  {
    key: 'placement',
    kind: 'dimension',
    label: 'Miejsce docelowe',
    format: 'text',
    description: 'Placement lub sieć reklamowa',
    platforms: ['meta', 'google'],
    sections: ['placement_table'],
    sourceFields: { meta: ['placement', 'publisher_platform', 'platform_position'], google: ['network'] },
    aggregation: 'none',
  },
  {
    key: 'age',
    kind: 'dimension',
    label: 'Wiek',
    format: 'text',
    description: 'Grupa wiekowa',
    platforms: ['meta', 'google'],
    sections: ['demographic_breakdown'],
    sourceFields: { meta: ['age'], google: ['ageRange'] },
    aggregation: 'none',
  },
  {
    key: 'gender',
    kind: 'dimension',
    label: 'Płeć',
    format: 'text',
    description: 'Płeć',
    platforms: ['meta', 'google'],
    sections: ['demographic_breakdown'],
    sourceFields: { meta: ['gender'], google: ['gender'] },
    aggregation: 'none',
  },
  {
    key: 'city',
    kind: 'dimension',
    label: 'Miasto',
    format: 'text',
    description: 'Miasto',
    platforms: ['google'],
    sections: ['geographic_map'],
    sourceFields: { google: ['cityName'] },
    aggregation: 'none',
  },
  {
    key: 'region',
    kind: 'dimension',
    label: 'Województwo',
    format: 'text',
    description: 'Województwo (Polska) lub region poza Polską',
    platforms: ['google'],
    sections: ['geographic_map'],
    sourceFields: { google: ['regionName', 'regionCode'] },
    aggregation: 'none',
  },
  {
    key: 'device',
    kind: 'dimension',
    label: 'Urządzenie',
    format: 'text',
    description: 'Typ urządzenia',
    platforms: ['google'],
    sections: ['device_table'],
    sourceFields: { google: ['device'] },
    aggregation: 'none',
  },
  {
    key: 'keyword',
    kind: 'dimension',
    label: 'Słowo kluczowe',
    format: 'text',
    description: 'Słowo kluczowe Google Ads',
    platforms: ['google'],
    sections: ['keyword_table'],
    sourceFields: { google: ['keyword'] },
    aggregation: 'none',
  },
  {
    key: 'search_term',
    kind: 'dimension',
    label: 'Wyszukiwane hasło',
    format: 'text',
    description: 'Rzeczywiste zapytanie użytkownika',
    platforms: ['google'],
    sections: ['search_terms_table'],
    sourceFields: { google: ['search_term'] },
    aggregation: 'none',
  },
  {
    key: 'match_type',
    kind: 'dimension',
    label: 'Typ dopasowania',
    format: 'text',
    description: 'Typ dopasowania hasła',
    platforms: ['google'],
    sections: ['search_terms_table'],
    sourceFields: { google: ['match_type'] },
    aggregation: 'none',
  },
  {
    key: 'ad_group_name',
    kind: 'dimension',
    label: 'Grupa reklam',
    format: 'text',
    description: 'Nazwa grupy reklam',
    platforms: ['google'],
    sections: ['search_terms_table'],
    sourceFields: { google: ['ad_group_name'] },
    aggregation: 'none',
  },
];

export const REGISTRY_FIELDS: RegistryField[] = [
  ...REGISTRY_METRICS,
  ...REGISTRY_DIMENSIONS,
];

export const REGISTRY_FIELD_BY_KEY = new Map(REGISTRY_FIELDS.map((field) => [field.key, field]));

export function getRegistryField(key: string): RegistryField | undefined {
  return REGISTRY_FIELD_BY_KEY.get(key);
}

export function getRegistryFieldsForSection(section: MetricSection): RegistryField[] {
  return REGISTRY_FIELDS.filter((field) => field.sections.includes(section));
}

export function getRegistryKeysForDiscovery(): string[] {
  return REGISTRY_METRICS.map((field) => field.key);
}
