/**
 * Google Ads `geo_target_constant.name` is English / ASCII-only. This table
 * maps normalized lookup keys (lowercase, Polish diacritics folded to ASCII)
 * to proper Polish city names for UI / PDF.
 *
 * Keys must match `normalizeCityLookupKey()` in `polish-geo-display.ts`.
 * Add entries when reports show new ASCII-only names from Google.
 */
export const POLISH_CITY_DISPLAY_BY_ASCII_KEY: Record<string, string> = {
  andrychow: 'Andrychów',
  bartoszyce: 'Bartoszyce',
  'biala podlaska': 'Biała Podlaska',
  bialystok: 'Białystok',
  'bielsko-biala': 'Bielsko-Biała',
  belchatow: 'Bełchatów',
  bochnia: 'Bochnia',
  brodnica: 'Brodnica',
  braniewo: 'Braniewo',
  busko: 'Busko-Zdrój',
  'busko-zdroj': 'Busko-Zdrój',
  bydgoszcz: 'Bydgoszcz',
  bytom: 'Bytom',
  chelm: 'Chełm',
  chelmno: 'Chełmno',
  chrzanow: 'Chrzanów',
  chorzow: 'Chorzów',
  ciechanow: 'Ciechanów',
  czestochowa: 'Częstochowa',
  debica: 'Dębica',
  'deblin': 'Dęblin',
  dzialdowo: 'Działdowo',
  elblag: 'Elbląg',
  elk: 'Ełk',
  garwolin: 'Garwolin',
  gdansk: 'Gdańsk',
  gdynia: 'Gdynia',
  gizycko: 'Giżycko',
  gniezno: 'Gniezno',
  'gorzow wielkopolski': 'Gorzów Wielkopolski',
  'gorzow wlkp': 'Gorzów Wielkopolski',
  grodzisk: 'Grodzisk Mazowiecki',
  'grodzisk mazowiecki': 'Grodzisk Mazowiecki',
  grojec: 'Grójec',
  grudziadz: 'Grudziądz',
  gubin: 'Gubin',
  hajnowka: 'Hajnówka',
  ilawa: 'Iława',
  inowroclaw: 'Inowrocław',
  jaroslaw: 'Jarosław',
  jastrzebie: 'Jastrzębie-Zdrój',
  'jastrzebie-zdroj': 'Jastrzębie-Zdrój',
  jaworzno: 'Jaworzno',
  jedrzejow: 'Jędrzejów',
  jelenia: 'Jelenia Góra',
  'jelenia gora': 'Jelenia Góra',
  jozefow: 'Józefów',
  kalisz: 'Kalisz',
  katowice: 'Katowice',
  kedzierzyn: 'Kędzierzyn-Koźle',
  'kedzierzyn-kozle': 'Kędzierzyn-Koźle',
  ketrzyn: 'Kętrzyn',
  kielce: 'Kielce',
  kolobrzeg: 'Kołobrzeg',
  kolo: 'Koło',
  konin: 'Konin',
  kostrzyn: 'Kostrzyn',
  kozienice: 'Kozienice',
  krasnik: 'Kraśnik',
  krosno: 'Krosno',
  'krosno odrzanskie': 'Krosno Odrzańskie',
  krakow: 'Kraków',
  kutno: 'Kutno',
  legionowo: 'Legionowo',
  legnica: 'Legnica',
  lidzbark: 'Lidzbark Warmiński',
  'lidzbark warminski': 'Lidzbark Warmiński',
  lodz: 'Łódź',
  losice: 'Łosice',
  lowicz: 'Łowicz',
  lubin: 'Lubin',
  lublin: 'Lublin',
  lubliniec: 'Lubliniec',
  lubsko: 'Lubsko',
  lukow: 'Łuków',
  marki: 'Marki',
  miechow: 'Miechów',
  miedzychod: 'Międzychód',
  miedzyrzecz: 'Międzyrzecz',
  mielec: 'Mielec',
  'minsk mazowiecki': 'Mińsk Mazowiecki',
  mlawa: 'Mława',
  mogilno: 'Mogilno',
  morag: 'Morąg',
  mragowo: 'Mrągowo',
  myslowice: 'Mysłowice',
  myszkow: 'Myszków',
  naklo: 'Nakło nad Notecią',
  'naklo nad notecia': 'Nakło nad Notecią',
  nidzica: 'Nidzica',
  'nowa sol': 'Nowa Sól',
  'nowe miasto lubawskie': 'Nowe Miasto Lubawskie',
  'nowy sacz': 'Nowy Sącz',
  'nowy targ': 'Nowy Targ',
  olsztyn: 'Olsztyn',
  olsztynek: 'Olsztynek',
  olkusz: 'Olkusz',
  opoczno: 'Opoczno',
  opole: 'Opole',
  ostroleka: 'Ostrołęka',
  'ostrow wielkopolski': 'Ostrów Wielkopolski',
  'ostrow wlkp': 'Ostrów Wielkopolski',
  'ostrowiec swietokrzyski': 'Ostrowiec Świętokrzyski',
  oswiecim: 'Oświęcim',
  otwock: 'Otwock',
  pabianice: 'Pabianice',
  piaseczno: 'Piaseczno',
  piekary: 'Piekary Śląskie',
  'piekary slaskie': 'Piekary Śląskie',
  pila: 'Piła',
  piotrkow: 'Piotrków Trybunalski',
  'piotrkow trybunalski': 'Piotrków Trybunalski',
  plock: 'Płock',
  plonsk: 'Płońsk',
  poznan: 'Poznań',
  pruszkow: 'Pruszków',
  przemysl: 'Przemyśl',
  pulawy: 'Puławy',
  raciborz: 'Racibórz',
  radom: 'Radom',
  radziejow: 'Radziejów',
  radzymin: 'Radzymin',
  rawa: 'Rawa Mazowiecka',
  'rawa mazowiecka': 'Rawa Mazowiecka',
  reda: 'Reda',
  rumia: 'Rumia',
  rzepin: 'Rzepin',
  rzeszow: 'Rzeszów',
  sandomierz: 'Sandomierz',
  sanok: 'Sanok',
  siedlce: 'Siedlce',
  siemianowice: 'Siemianowice Śląskie',
  'siemianowice slaskie': 'Siemianowice Śląskie',
  sieradz: 'Sieradz',
  skarzysko: 'Skarżysko-Kamienna',
  'skarzysko kamienna': 'Skarżysko-Kamienna',
  skierniewice: 'Skierniewice',
  skwierzyna: 'Skwierzyna',
  slonsk: 'Słońsk',
  slupsk: 'Słupsk',
  sochaczew: 'Sochaczew',
  sosnowiec: 'Sosnowiec',
  'sokolow podlaski': 'Sokołów Podlaski',
  stalowa: 'Stalowa Wola',
  'stalowa wola': 'Stalowa Wola',
  starachowice: 'Starachowice',
  stargard: 'Stargard',
  strzelce: 'Strzelce Krajeńskie',
  'strzelce krajenskie': 'Strzelce Krajeńskie',
  strzelno: 'Strzelno',
  sulechow: 'Sulechów',
  suwalki: 'Suwałki',
  swiebodzin: 'Świebodzin',
  swiecie: 'Świecie',
  swietochlowice: 'Świętochłowice',
  swinoujscie: 'Świnoujście',
  szczecin: 'Szczecin',
  tarnobrzeg: 'Tarnobrzeg',
  tarnow: 'Tarnów',
  tarnowskie: 'Tarnowskie Góry',
  'tarnowskie gory': 'Tarnowskie Góry',
  tomazow: 'Tomaszów Mazowiecki',
  'tomaszow mazowiecki': 'Tomaszów Mazowiecki',
  torun: 'Toruń',
  turek: 'Turek',
  tychy: 'Tychy',
  wabrzezno: 'Wąbrzeźno',
  wadowice: 'Wadowice',
  walbrzych: 'Wałbrzych',
  warszawa: 'Warszawa',
  wegrow: 'Węgrów',
  wloclawek: 'Włocławek',
  wlodawa: 'Włodawa',
  wloszczowa: 'Włoszczowa',
  wodzislaw: 'Wodzisław Śląski',
  'wodzislaw slaski': 'Wodzisław Śląski',
  wolomin: 'Wołomin',
  wroclaw: 'Wrocław',
  wschowa: 'Wschowa',
  wyszkow: 'Wyszków',
  zabrze: 'Zabrze',
  zagan: 'Żagań',
  zamos: 'Zamość',
  zary: 'Żary',
  zawiercie: 'Zawiercie',
  zabki: 'Ząbki',
  zdunska: 'Zduńska Wola',
  'zdunska wola': 'Zduńska Wola',
  zgierz: 'Zgierz',
  'zielona gora': 'Zielona Góra',
  zakopane: 'Zakopane',
  znin: 'Żnin',
  zory: 'Żory',
  zyrardow: 'Żyrardów',
};
