#!/bin/bash
echo "🔍 Checking Belmonte account status in production..."
echo ""
echo "Note: This requires Supabase access to check the database"
echo ""
echo "To check Belmonte account manually:"
echo ""
echo "1. Visit your production app:"
echo "https://piotr-276pjhx8m-jachonkisz-gmailcoms-projects.vercel.app"
echo ""
echo "2. Login as admin"
echo ""
echo "3. Go to: Admin → Clients"
echo ""
echo "4. Look for 'Belmonte' account"
echo ""
echo "5. Check if it has:"
echo "   - google_ads_enabled = true"
echo "   - google_ads_customer_id set"
echo "   - google_ads_refresh_token set"
echo ""
echo "If yes, you can use Belmonte account for Google audit!"
